version: 0.2
phases:
  install:
    runtime-versions:
        dotnet: 3.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AHello.csproj
      - echo Test started on `date`
      - dotnet test
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)      
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./out AHello.csproj
      - echo build Docker image on `date`
      - docker build -t ahello:latest .
      - docker tag ahello:latest 808662307749.dkr.ecr.us-east-1.amazonaws.com/ahello:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 808662307749.dkr.ecr.us-east-1.amazonaws.com/ahello:latest
